### ISSUE TITLE
Drupal Taxonomy Access Control Lite module deprecated

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/tac_lite#3]
Today (Jan 26th, 2022) the Drupal TAC Lite module was marked unsupported.

I have [offered to co-maintain the TAC Lite module for Drupal](https://www.drupal.org/project/projectownership/issues/3260729) in the hopes that I can help fix and/or test the solution to the unresolved security issue. 

Once There is a solution that the Drupal security team approves of, both projects should have a matching release. I'm hoping I can help coordinate those releases @stpaultim

**Comment by stpaultim** [comment]
@jenlampton - Is this a module that have used before. 

It looks like I tried to port this 3 years ago in response to a query in the forum and never really got very far. I've never used this module on any Drupal or Backdrop sites. 

Do we know if it's worth investing time in this module?

**Comment by jenlampton** [comment]
@stpaultim I would prefer it not sit in contrib with a known security vulnerability. If we aren't going to fix it, maybe we should remove it altogether? I do think we might be able to run the updated Drupal version through coder upgrade though to replace this. Do you remember how much work it was to get it to this state?

**Comment by stpaultim** [comment]
@jenlampton - I'm quite sure that minimal amount of work was put into it. 

I'm very confused about the concern over an unreleased module. The notes suggest that this module doesn't even work, so it can't be much of a security threat. 

I will add a note at the top of the README that alerts anyone interested that this module should not be used. 

BUT, if we are going to remove an unreleased module that doesn't work and is NOT available on BackdropCMS.org, because of a security issue in the Drupal issue queue, it makes me wonder if I should be putting partially ported modules here at all?

**Comment by stpaultim** [comment]
This WAS the first line of the README file:

```
NOTE: This module has been run through the Coder Upgrader and nothing 
more. It is throwing errors and is NOT stabile. Please, feel free to
test and create issues. Hopefully, we can find someone who can get this
running.
```

**Comment by stpaultim** [comment]
So as a temporary step forward, I have changed the beginning of the README to:

```
NOTE: This module SHOULD NOT be used in it's current condition. 

1) The Drupal 7 version is unsupported due to known security issues.
   drupal.org/project/tac_lite
2) This modules does not work and is NOT stable. 

An effort is being made to find a new maintainer and fix the Drupal 7
version and this module should only be used after these issues
are resolved and ported to the Backdrop version. 

This module has been run through the Coder Upgrader and nothing 
more. backdropcms.org/project/coder_upgrade
```

Again, I really don't have anything invested in this module and won't care if it's deleted. HOWEVER, I am concerned because deleting this module for this reason would make me very wary of putting other incomplete modules into this space. 

I would certainly be tempted to delete the other partially ported modules I have in the Backdrop Contrib space, and there are a handful.

**Comment by stpaultim** [comment]
I suppose a clear policy statement could alleviate my concerns, if I understand when it is and is not acceptable to put an partially complete and unstable module here. I can see where this situation might be considered different from other unstable modules, I would just need help understanding the difference.

**Comment by jenlampton** [comment]
> I'm very confused about the concern over an unreleased module. 

@stpaultim just to be clear, the risk of this actually causing a problem is very low. It's not strictly necessary to do anything at all!

> I would prefer it not sit in contrib with a known security vulnerability.

I'm sorry if I mislead you, I was only stating my *personal* preference here. If I'm involved in fixing tac_lite for Drupal 7, it might be worth taking that version and running it through coder_upgrade again. I was asking how much work that was, because if you aren't interested in doing it, I was thinking about doing it.

> I am concerned because deleting this module for this reason would make me very wary of putting other incomplete modules into this space.

You should always feel comfortable putting your code in contrib. When there is a security issue, our security team will help you :)

This is me! *puts on security team hat* I'm here to help!

**Comment by stpaultim** [comment]
@jenlampton - thanks for clarifications. 

As I mentioned, I've done very little work on this module. It's no loss to simply delete repo and start over (I'll keep a copy just in case). Please, feel free to delete.

**Comment by jenlampton** [comment]
very well!
